sudo: required

language: bash

services:
  - docker

script:
 - docker build -t nixel2007/gitlab .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push nixel2007/gitlab;
    fi
